language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - npm install -g npm@latest
  - npm install
  - npm install -g expo-cli
script:
  - expo start
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - expo start
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive